import HeaderStrip from './header-strip'
import Header from './header'
import './globals.css'
import Footer from './footer'
import FooterStrip from './footer_strip'
import { Outlet } from 'react-router-dom'
import WhatsAppIcon from '../components/wa_icon'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`min-h-screen`}>
        <HeaderStrip />
        <Header />
          <Outlet />
        <Footer />
        <FooterStrip />
        <WhatsAppIcon />
        </body>
    </html>
  )
}
